# Generated by Django 3.1.2 on 2020-10-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='is_paid',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, help_text='Currency: Taka', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Currency: Taka', max_digits=8),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Unit: kg'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Unit: kg'),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, help_text='Currency: Taka', max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Unit: kg'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, help_text='Currency: Taka', max_digits=8),
        ),
    ]
