# Generated by Django 3.1.2 on 2020-10-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201009_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproduct',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
