# Generated by Django 3.1.2 on 2020-10-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201009_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
