# Generated by Django 3.1.2 on 2020-11-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201010_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='product_label',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
