# Generated by Django 3.1.2 on 2020-12-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201122_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseproduct',
            options={'ordering': ['-date_added']},
        ),
    ]
