# Generated by Django 3.1.2 on 2020-12-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201218_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellproduct',
            old_name='customer_phone',
            new_name='token_number',
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
