# Generated by Django 3.1.2 on 2020-12-18 14:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201218_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sellproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='chalan_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='date_added',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='date_added',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier'),
        ),
    ]
