# Generated by Django 3.1.2 on 2020-12-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201218_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='product_name',
            field=models.CharField(default='গম', max_length=30),
        ),
    ]
