# Generated by Django 3.1.2 on 2020-12-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_supplier_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
