# Generated by Django 3.1.2 on 2020-12-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201219_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
