# Generated by Django 3.1.2 on 2020-12-19 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201219_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
