# Generated by Django 3.1.2 on 2020-12-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201219_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseproduct',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='sellproduct',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-date_updated']},
        ),
    ]
