# Generated by Django 3.1.2 on 2020-12-20 05:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201219_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='sack',
            field=models.IntegerField(choices=[(5, 5), (35, 35), (37, 37), (55, 55), (50, 50), (55, 55), (60, 60)], default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='office',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='date_added',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='purchaseproduct',
            name='date_updated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='date_added',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='date_updated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
