# Generated by Django 3.1.2 on 2020-12-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201220_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='sack',
            field=models.IntegerField(choices=[(5, '5 kg'), (35, '35 kg'), (37, '37 kg'), (55, '55 kg'), (50, '50 kg'), (55, '55 kg'), (60, '60 kg')]),
        ),
    ]
