# Generated by Django 3.1.2 on 2020-12-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201220_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseproduct',
            options={'ordering': ['-date_added', '-id']},
        ),
        migrations.AlterModelOptions(
            name='sellproduct',
            options={'ordering': ['-date_added', '-id']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-date_updated', '-id']},
        ),
    ]
