# Generated by Django 3.1.2 on 2020-12-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201220_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='sell_price',
        ),
    ]
