# Generated by Django 3.1.2 on 2020-12-21 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_stock_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
