# Generated by Django 3.1.2 on 2020-12-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_supplier_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-date_added', '-id']},
        ),
    ]
