# Generated by Django 3.1.2 on 2021-01-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210121_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='product_name',
            field=models.CharField(default='Wheat', max_length=30),
        ),
    ]
