# Generated by Django 3.1.2 on 2021-04-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_loginexpire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginexpire',
            name='site',
        ),
    ]
